inherit_gem:
  spbtv_code_style: .strict_rubocop.yml

Style/MethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false
